/**
 * vendor-fonts.mjs — one-off helper.
 *
 * The publication's typefaces (Playfair Display, Source Serif 4, Inter,
 * Special Elite) were loaded from fonts.googleapis.com at runtime. Google Fonts
 * is on a great many blocklists, and a blocked stylesheet silently drops the
 * entire typographic identity of the newspaper back to system serif/sans — the
 * design stops reading as "The Wire" at all.
 *
 * This downloads the *Latin* subset of each face into public/vendor/fonts/ and
 * rewrites the @font-face src to a local path. Latin only is deliberate: the
 * Cyrillic/Greek/Vietnamese files would multiply the payload for glyphs a
 * Nakuru newsroom never prints.
 *
 * Run with:  node vendor-fonts.mjs
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), 'public', 'vendor', 'fonts');
const SRC_CSS = join(dirname(fileURLToPath(import.meta.url)), 'src', 'vendor-fonts.css');

/* Must match the link that was in index.html before it was self-hosted. */
const FAMILIES =
  'Playfair+Display:ital,wght@0,400..900;1,400..900' +
  '&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400' +
  '&family=Inter:wght@400;500;600;700;800' +
  '&family=Special+Elite&display=swap';

const GOOGLE_CSS = `https://fonts.googleapis.com/css2?family=${FAMILIES}`;

/* A modern desktop UA makes Google serve woff2; an older one gets ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

mkdirSync(ROOT, { recursive: true });

console.log('Fetching Google Fonts CSS...');
const cssRes = await fetch(GOOGLE_CSS, { headers: { 'User-Agent': UA } });
if (!cssRes.ok) {
  console.error(`Failed: ${cssRes.status} ${cssRes.statusText}`);
  process.exit(1);
}
const upstream = await cssRes.text();

/**
 * Google emits one `/* subset *\/` comment before each @font-face block, so the
 * blocks are split apart and each one's preceding comment tells us the subset.
 * Only `latin` is kept.
 */
const parts = upstream.split('@font-face');
const kept = [];

for (let i = 1; i < parts.length; i++) {
  const block = `@font-face${parts[i]}`;
  const before = parts[i - 1];
  const subsetMatch = before.match(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*$/i);
  const subset = subsetMatch ? subsetMatch[1] : '';

  if (subset !== 'latin') continue;

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
  if (!url) continue;

  const weight = (block.match(/font-weight:\s*([^;]+);/) || [, '400'])[1].trim();
  const style = (block.match(/font-style:\s*([^;]+);/) || [, 'normal'])[1].trim();
  const family = (block.match(/font-family:\s*'([^']+)'/) || [, 'unknown'])[1];

  // Variable fonts report a range like "400..900", which is not
  // filesystem-safe, so normalise it to "400-900".
  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const weightSlug = weight.replace(/\s*\.\.\s*/, '-').replace(/\s+/g, '');
  const file = `${slug}-${weightSlug}-${style}.woff2`;

  kept.push({ block, family, weight, style, file, remote: url[1] });
}

console.log(`Keeping ${kept.length} Latin faces.`);

const downloaded = [];
for (const face of kept) {
  const res = await fetch(face.remote, { headers: { 'User-Agent': UA } });
  if (!res.ok) {
    console.error(`  MISSING ${face.file}: ${res.status}`);
    continue;
  }
  writeFileSync(join(ROOT, face.file), Buffer.from(await res.arrayBuffer()));
  downloaded.push(face);
}

const out = downloaded
  .map((face) =>
    face.block
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/vendor/fonts/${face.file}')`)
      .trim()
  )
  .join('\n\n');

writeFileSync(
  SRC_CSS,
  `/* Generated by vendor-fonts.mjs - do not edit by hand.
   Self-hosted Latin subsets of Playfair Display, Source Serif 4, Inter and
   Special Elite, so a blocked Google Fonts request cannot strip the
   publication of its typography. Regenerate with: node vendor-fonts.mjs */\n\n${out}\n`,
  'utf8'
);

const total = downloaded.reduce(
  (sum, f) => sum + readFileSync(join(ROOT, f.file)).length,
  0
);
console.log(`\nWrote ${downloaded.length} woff2 files (${(total / 1024).toFixed(0)} kB total)`);
console.log('Stylesheet: src/vendor-fonts.css');

if (!existsSync(SRC_CSS)) process.exit(1);
